require('lazy-config')
require('mason-config')
require('custom-configs.key-mappings')
require('custom-configs.plugins-config')
require('custom-configs.editor.editor-config')
require('custom-configs.lspconfig')
require('custom-configs.color-scheme')
